name: elmed219
dependencies:
- python >= 3.7.0
- pip
- ipython
- ipywidgets
- jupyter
- git
- numpy
- matplotlib
- pandas
- scikit-learn >= 0.20
- ipykernel
- scipy
- seaborn
- scikit-image
- imageio
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::jupyterlab
- conda-forge::statsmodels
- pip:
  - pip >= 19.0
  - kaggle
  - xlrd
  - eli5
  - pdpbox
  - nibabel
  - nilearn
  - opencv-python
  - pandas-profiling
  